#ifndef MAKU_LOCALIZATION_H
#define MAKU_LOCALIZATION_H

typedef enum {
    LANG_RU = 0,
    LANG_EN = 1,
    LANG_COUNT
} MakuLang;

typedef enum {
    STR_APP_TITLE = 0,
    STR_MENU_INFO,
    STR_MENU_PERF,
    STR_MENU_COMPONENTS,
    STR_MENU_PROCESSES,
    STR_MENU_PERSONALIZE,
    STR_MENU_DEBLOAT,
    STR_MENU_CLEANUP,
    STR_MENU_SECURITY,
    STR_MENU_FILEMGR,
    STR_MENU_RECOVERY,
    STR_MENU_GNOME,
    STR_DISTRO_LABEL,
    STR_SESSION_LABEL,
    STR_SESSION_UNSUPPORTED,
    STR_CPU_LABEL,
    STR_RAM_LABEL,
    STR_UPTIME_LABEL,
    STR_TOGGLE_MAX_CPU,
    STR_TOGGLE_SWAPPINESS,
    STR_TOGGLE_FILE_LIMITS,
    STR_TOGGLE_SPLIT_LOCK,
    STR_TOGGLE_BBR,
    STR_SVC_CUPS,
    STR_SVC_AVAHI,
    STR_SVC_SAMBA,
    STR_SVC_ABRT,
    STR_PROC_KILL,
    STR_PROC_FREEZE,
    STR_PROC_UNFREEZE,
    STR_PERSONALIZE_COLOR,
    STR_PERSONALIZE_DARK,
    STR_DEBLOAT_BROKEN,
    STR_DEBLOAT_REMOVE,
    STR_CLEANUP_LOGS,
    STR_CLEANUP_CACHE,
    STR_CLEANUP_PKGCACHE,
    STR_CLEANUP_TRIM,
    STR_SEC_FEDORA,
    STR_SEC_HOSTS,
    STR_SEC_HISTORY,
    STR_FM_HIDDEN,
    STR_FM_GRID,
    STR_FM_LIST,
    STR_RECOVERY_BACKUP,
    STR_RECOVERY_RESET,
    STR_RECOVERY_DROPCACHE,
    STR_GNOME_NOT_DETECTED,
    STR_GNOME_HOT_CORNERS,
    STR_GNOME_NAUTILUS_COUNT,
    STR_GNOME_FRACTIONAL_SCALING,
    STR_GNOME_ANIMATIONS,
    STR_GNOME_NIGHT_LIGHT,
    STR_GNOME_SHOW_BATTERY_PERCENT,
    STR_COUNT
} MakuStringId;

extern const char *g_localization[LANG_COUNT][STR_COUNT];

const char *maku_tr(MakuStringId id);
void maku_set_lang(MakuLang lang);
MakuLang maku_get_lang(void);

#endif
